import Head from 'next/head'
import Image from 'next/image'
import NavBar from '@/components/NavBar'
import CountriesList from '@/components/CountriesList'
import { Typography } from '@mui/material'



export default function Home({ setMode, mode }) {
  return (
    <>
      <Head>
        <title>Countries List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar setMode={setMode} mode={mode} />
        <CountriesList />
      </div>
    </>
  )
}
