import Head from 'next/head'
import NavBar from '@/components/NavBar'
import CountriesList from '@/components/CountriesList'

export default function Home() {
  return (
    <>
      <Head>
        <title>Countries List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CountriesList />
      </div>
    </>
  )
}
